### PR TITLE
Support out of source build

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by mathstuf** [comment]
Actually, the first commit is just a new `g-ir-*` tools [change](https://copr-be.cloud.fedoraproject.org/results/mathstuf/eventd/fedora-rawhide-x86_64/00111004-eventd/build.log.gz).

**Comment by sardemff7** [comment]
Pushed d51e67ff0258a312621a3d21bb7cfc6954156e33 and c4d46442121c5af7d0ccf0a7e75fc7766218391f.

Waiting for the full rationale behind the `CPPFLAGS` change.

**Comment by mathstuf** [comment]
See the build error at the link in the first comment here:

```
GISCAN EventdEvent-0.gir
gcc: error: G_LOG_DOMAIN="libeventd-event": No such file or directory
```

**Comment by mathstuf** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=754828

**Comment by mathstuf** [comment]
Closing as the important commits are merged and the gobject-introspection bug is fixed (just waiting for a Rawhide update…).

**Pull request closed without merging**
