### PR TITLE
Fix man typos

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by mathstuf** [comment]
Updated.

**Comment by sardemff7** [comment]
Pushed 794c2723685b4fe134566616c6bae6a39c84711a.

I still not want to separate every single man page on its own line, so closing. :-)

**Comment by mathstuf** [comment]
Each isn't on its own line here… There's just a space between them with that.

**Comment by mathstuf** [comment]
At least as I remember it. Will double check, but all it did for me in `less` was add a space between them.

**Comment by sardemff7** [comment]
Here it put it on several lines.

**Comment by mathstuf** [comment]
Here's what it looks like here without any fix at all:

```
       evp plugin man pages
           eventd-evp(1)eventd-evp.conf(5)eventd-evp.event(5)

       fdo-notifications plugin man pages
           eventd-fdo-notifications(1)

       relay plugin man pages
           eventd-relay.event(5)

       exec plugin man pages
           eventd-exec.event(5)

       nd plugin and backends man pages
           eventd-nd.conf(5)eventd-nd.event(5) eventd-nd-xcb.conf(5)

       im plugin man pages
           eventd-im.conf(5)eventd-im.event(5)
```

Note that `eventd-nd-xcb.conf(5)` has only a space between it even though it has a separate `para` section in `common-man.xml` (because it is conditional).

**Comment by mathstuf** [comment]
Ah, in the HTML generated, it *is* on a separate line.

**Pull request closed without merging**
