### PR TITLE
[WIP] Gir files

### PR DESCRIPTION
**Pull request by mathstuf**
---
Docs are written with #7 and #8 in mind. Some TODO items yet.

### CODE REVIEW

**Comment by mathstuf** [comment]
Updated. Still some TODO items in the WIP commits.

**Comment by mathstuf** [comment]
Well, it looks like things work with some light poking :) .

**Comment by sardemff7** [comment]
I did not review the doc comments themselves yet.
All of that seems pretty good so far. You should amend you commits more often, at least for me, since I find it confusing to have follow-up fixes in an unrelated commit. (I prefer to review commit-by-commit, it is easier to me.)

Thanks for working on this! :-)

**Comment by mathstuf** [comment]
Rebased. Still kept the `glib.h` headers to avoid warnings while developing at least.

**Comment by sardemff7** [comment]
All of that looks really nice so far.
Of course, do not hesitate to ask for a precision either here or on IRC (you can hang in the channel if you want, I will answer as soon as I read your messages).

**Comment by mathstuf** [comment]
I've started sitting on IRC again at home. Too distracting at work :) .

**Comment by mathstuf** [comment]
OK, updated for all comments. Should just be TODO items in the docs.

**Comment by sardemff7** [comment]
I hope I answered clearly enough to all TODOs. :-)

I will now be picky about commit messages I think, although I will probably re-write them on merge anyway (I do not use GitHub merge feature).

Please note that libraries will *probably* change to the LGPL v3+ licence at some point (instead of plain GPL v3+). I will then need your agreement for such a licence change.

**Comment by mathstuf** [comment]
I'm fine with LGPLv3+ (esp. since plugins are involved). I also added gtk-doc support.

**Comment by sardemff7** [comment]
Pushed as 8ee8c669523d711b9efb2a75af1fe9fa2b03c9d0, 5b9316e12567fa5f66bd94b6c4a786b7a4dce4a7, 42f42ff254b3c6c998a39343765bb7483af7701c and 6496826ee9c0f36de12066d40d790093c5f7d561.

I squashed all the `Makefile.am`/`*.mk` changes in a single commit and put it at the end (so every commit can compile on its own).
(I also rewrote commit messages, told you I was picky.)

gtk-doc support is missing quite a few parts. You should probably make a new PR if you want to do that too, otherwise I will do it *soon*™.

I keep this PR opened to keep track of the last two missing items:

- `EventdEventEndReason` description
- `EventdEvent` signals description

**Comment by mathstuf** [comment]
Updated.

**Comment by sardemff7** [comment]
Pushed as 8865f482764ac011a7c163c83849cc8d36998b96.

Thanks a lot for all this great work!
One last bit on my local work and I will have a fully functional set of script language plugins!

**Pull request closed without merging**
